#' Resolve and Decode Barcodes for Images Listed in Excel Files
#' (Symbol-Level, Stateful Propagation, One-to-Many Join)
#'
#' `resolve_folder_sequence()` reads one or more Excel workbooks that list
#' image files (typically generated by [write_directory_index()]), decodes
#' all barcodes and QR codes for each image (one row per symbol), and applies
#' stateful symbol-level propagation across sequentially numbered filenames.
#'
#' For each workbook under `path`, the function:
#'
#' - Assumes one row per image in the workbook (as produced by
#'   [write_directory_index()]).
#' - Decodes all symbols in each image using [decode_hierarchical_zxing()]:
#'   - If an image contains multiple symbols, it yields multiple rows.
#'   - If no symbols are detected, a single row with `NA` symbol fields is created.
#' - Parses `file_name` into `prefix` and `number` with the pattern
#'   `^([A-Za-z]+)_([0-9]+)$` (e.g. `IMG_0001.JPG`).
#' - Applies stateful per-prefix logic:
#'   \itemize{
#'     \item If an image has at least one decoded symbol, it becomes the current
#'           "donor" for that prefix.
#'     \item If the next image has the same prefix, `number = previous_number + 1`,
#'           and no decoded symbols, it inherits the entire set of symbol rows
#'           from the donor.
#'     \item If the prefix changes, or the numeric sequence jumps by more than 1,
#'           or there is no donor, no inheritance occurs and the image keeps only
#'           its own decoded rows (which may be a single `NA` row).
#'   }
#'
#' For **break images** (prefix change or jump > 1) that have no usable symbols,
#' `index` remains `NA`, and `code_format`, `text`, and `type` are set to
#' `"unknown"` to make this state explicit in the output.
#'
#' The final symbol-level table is joined back to the original workbook,
#' resulting in a one-to-many join: each input image row may correspond to
#' zero, one, or many symbol rows.
#'
#' ## Logging
#'
#' A log file named `resolve_log.csv` is written to the `path` directory. One
#' row is appended per image processed, with columns:
#'
#' - `time`       – timestamp of decoding
#' - `workbook`   – path to the Excel index workbook
#' - `image_file` – file_name (e.g. `IMG_0123.JPG`)
#' - `full_path`  – full image path
#' - `prefix`     – parsed filename prefix
#' - `number`     – parsed numeric component
#' - `decoded`    – TRUE if at least one symbol was decoded; FALSE otherwise
#'
#' This per-image log supports live progress monitoring via
#' [monitor_resolve_progress()].
#'
#' ## Filename requirements
#'
#' Filenames must match `PREFIX_NUMBER.ext`, e.g. `IMG_0001.JPG`, `DSC_01234.jpg`,
#' where:
#'
#' \preformatted{
#'   ^([A-Za-z]+)_([0-9]+)\\.
#' }
#'
#' Files not matching this pattern receive `NA` for `prefix` and `number` and
#' do not participate in sequence-based inheritance (they still decode normally).
#'
#' @param path Directory containing `.xlsx` index workbooks.
#' @param pattern Regular expression used to identify workbook files.
#'
#' @return Invisibly returns a named list of tibbles (one per workbook), each
#' containing:
#'
#' - all original workbook columns, and
#' - symbol-level propagated barcode/QR fields:
#'   \itemize{
#'     \item `index`
#'     \item `code_format`
#'     \item `text`
#'     \item `type`
#'     \item `prefix`
#'     \item `number`
#'   }
#'
#' @seealso
#'   [decode_hierarchical_zxing()],
#'   [write_directory_index()],
#'   [monitor_resolve_progress()],
#'   [safe_write_xlsx()]
#'
#' @importFrom readr read_csv write_csv
#' @importFrom dplyr bind_rows group_by summarise arrange left_join
#' @importFrom tibble tibble
#' @export
resolve_folder_sequence <- function(path, pattern = "\\.csv$", con = NULL,
                                    overwrite = FALSE) {

  if (!dir.exists(path)) {
    stop("Path does not exist: ", path)
  }

  # -------------------------------------------------------------------------
  # Discover index CSV files
  # -------------------------------------------------------------------------
  # Always scan recursively so we reach leaf folders under a deep root.
  csv_files <- list.files(path, pattern = pattern, recursive = TRUE, full.names = TRUE)

  # Keep only CSVs produced by write_directory_index().  The naming
  # convention is that each index CSV's filename stem matches its parent
  # folder name — e.g. "Phil Copy/Phil Copy.csv".  This automatically
  # excludes log files (resolve_log.csv, scan_log.csv), catalogue.csv,
  # heartbeat files, and any other incidental CSV in the tree, without
  # needing a hard-coded exclusion list.
  csv_files <- csv_files[
    tools::file_path_sans_ext(basename(csv_files)) == basename(dirname(csv_files))
  ]

  if (length(csv_files) == 0L) {
    stop("No CSV index files found in: ", path)
  }

  message("Found ", length(csv_files), " CSV index file(s).")

  # -------------------------------------------------------------------------
  # Logging: one row per image
  # -------------------------------------------------------------------------
  log_file <- file.path(path, "resolve_log.csv")

  # -------------------------------------------------------------------------
  # Filename prefix-number parser: "IMG_0001.JPG" -> prefix="IMG", number=1
  # -------------------------------------------------------------------------
  parse_sequence <- function(fname) {
    stem  <- tools::file_path_sans_ext(basename(fname))
    m     <- regexec("^([A-Za-z]+)_([0-9]+)$", stem)
    parts <- regmatches(stem, m)[[1]]
    if (length(parts) != 3L) {
      return(list(prefix = NA_character_, number = NA_integer_))
    }
    list(prefix = parts[2], number = as.integer(parts[3]))
  }

  # -------------------------------------------------------------------------
  # Process each Excel workbook
  # -------------------------------------------------------------------------
  results <- vector("list", length(csv_files))
  names(results) <- csv_files

  for (i in seq_along(csv_files)) {

    csv_file <- csv_files[i]
    message("\n[", i, "/", length(csv_files), "] Processing: ", csv_file)

    df_orig <- readr::read_csv(csv_file, show_col_types = FALSE)

    if (!"file_name" %in% names(df_orig)) {
      stop("Index missing required column 'file_name': ", csv_file)
    }

    # -----------------------------------------------------------------------
    # Incremental mode: skip images already decoded in a previous run.
    # A previously resolved CSV has a `code_format` column. Rows where
    # code_format is non-NA were decoded in a prior run; rows where it is NA
    # are new images added by write_directory_index() since the last run.
    # "unknown" means a break/undecoded image — also already processed.
    # -----------------------------------------------------------------------
    previously_resolved <- !overwrite && "code_format" %in% names(df_orig)

    if (previously_resolved) {
      already_done  <- unique(df_orig$file_name[!is.na(df_orig$code_format)])
      new_names     <- setdiff(unique(df_orig$file_name), already_done)

      if (length(new_names) == 0L) {
        message("  All images already decoded — skipping (use overwrite = TRUE to re-run).")
        results[[i]] <- df_orig
        next
      }

      message("  ", length(new_names), " new image(s) to decode (",
              length(already_done), " already processed).")

      # One row per new file for the decode loop
      df_to_decode <- df_orig[df_orig$file_name %in% new_names, , drop = FALSE]
      df_to_decode <- df_to_decode[!duplicated(df_to_decode$file_name), , drop = FALSE]

      # Reconstruct long_df for old images from the existing CSV.
      # Exclude "unknown" rows — they represent break images (no symbol) and
      # must not be treated as donors in the re-propagation.
      old_cols <- intersect(
        c("file_name", "full_path", "dir", "index", "code_format", "text", "type"),
        names(df_orig)
      )
      old_long <- df_orig[
        !is.na(df_orig$code_format) & df_orig$code_format != "unknown",
        old_cols, drop = FALSE
      ]

    } else {
      already_done  <- character(0)
      new_names     <- unique(df_orig$file_name)
      df_to_decode  <- df_orig[!duplicated(df_orig$file_name), , drop = FALSE]
      old_long      <- NULL
    }

    n_images <- nrow(df_to_decode)
    message("  Decoding ", n_images, " image(s)...")

    # -----------------------------------------------------------------------
    # Decode each image → symbol-level long rows
    # Runs in parallel if the user has set a future::plan() beforehand;
    # falls back to sequential lapply() if furrr is not installed.
    # -----------------------------------------------------------------------
    decode_one <- function(j) {
      fname     <- df_to_decode$file_name[j]
      full_path <- file.path(df_to_decode$dir[j], fname)

      decoded_tbl <- tryCatch(
        decode_hierarchical_zxing(full_path),
        error = function(e) {
          tibble::tibble(
            index       = NA_integer_,
            code_format = NA_character_,
            text        = NA_character_,
            type        = NA_character_
          )
        }
      )

      seq_parsed   <- parse_sequence(fname)
      decoded_flag <- any(!is.na(decoded_tbl$text) & decoded_tbl$text != "")

      decoded_tbl$file_name <- fname
      decoded_tbl$full_path <- full_path
      decoded_tbl$dir       <- df_to_decode$dir[j]

      list(
        decoded_tbl = decoded_tbl,
        log_entry   = data.frame(
          time       = format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
          csv_file   = csv_file,
          image_file = fname,
          full_path  = full_path,
          prefix     = seq_parsed$prefix,
          number     = seq_parsed$number,
          decoded    = decoded_flag,
          stringsAsFactors = FALSE
        )
      )
    }

    decode_results <- if (requireNamespace("furrr", quietly = TRUE)) {
      furrr::future_map(
        seq_len(n_images),
        decode_one,
        .options = furrr::furrr_options(packages = "kiwiDecoder", seed = TRUE)
      )
    } else {
      lapply(seq_len(n_images), decode_one)
    }

    decoded   <- lapply(decode_results, `[[`, "decoded_tbl")
    log_batch <- dplyr::bind_rows(lapply(decode_results, `[[`, "log_entry"))

    # Write entire batch at once (one file open/close per CSV, not per image).
    # readr::write_csv with append = file.exists() correctly omits column names
    # on subsequent writes without triggering R's "appending column names" warning.
    readr::write_csv(log_batch, log_file, append = file.exists(log_file))

    long_df_new <- dplyr::bind_rows(decoded)

    # Combine new decoded results with cached results for old images
    long_df <- if (!is.null(old_long) && nrow(old_long) > 0L) {
      dplyr::bind_rows(old_long, long_df_new)
    } else {
      long_df_new
    }

    # -----------------------------------------------------------------------
    # Build image-level sequencing table
    # Use the FULL set of unique images (old + new) so propagation runs
    # across the entire sequence, not just the newly decoded images.
    # -----------------------------------------------------------------------
    img_unique_cols <- intersect(
      c("dir", "file_name", "ext"),
      names(df_orig)
    )
    image_df <- df_orig[!duplicated(df_orig$file_name), img_unique_cols, drop = FALSE]
    seq_info <- lapply(image_df$file_name, parse_sequence)
    image_df$prefix <- vapply(seq_info, `[[`, "prefix", FUN.VALUE = character(1))
    image_df$number <- vapply(seq_info, `[[`, "number", FUN.VALUE = integer(1))

    dec_summary <- long_df |>
      dplyr::group_by(file_name) |>
      dplyr::summarise(
        has_symbol = any(!is.na(text) & text != ""),
        .groups    = "drop"
      )

    image_df <- dplyr::left_join(image_df, dec_summary, by = "file_name")
    image_df$has_symbol[is.na(image_df$has_symbol)] <- FALSE

    image_df <- dplyr::arrange(image_df, prefix, number)

    # -----------------------------------------------------------------------
    # Stateful donor tracking
    # -----------------------------------------------------------------------
    current_donor  <- NA_character_
    current_prefix <- NA_character_
    last_number    <- NA_integer_

    image_df$donor      <- NA_character_
    image_df$break_case <- FALSE

    for (r in seq_len(nrow(image_df))) {
      fn  <- image_df$file_name[r]
      px  <- image_df$prefix[r]
      num <- image_df$number[r]
      has <- image_df$has_symbol[r]

      if (has) {
        # decoded image → new donor
        current_donor           <- fn
        current_prefix          <- px
        last_number             <- num
        image_df$donor[r]       <- fn
        image_df$break_case[r]  <- FALSE

      } else if (!is.na(current_donor) &&
                 px == current_prefix &&
                 !is.na(num) && num == last_number + 1) {

        # same prefix, +1, no symbols → inherit from donor
        image_df$donor[r]       <- current_donor
        image_df$break_case[r]  <- FALSE
        last_number             <- num

      } else {
        # gap > 1, prefix change, or no donor → break in sequence
        current_donor           <- NA_character_
        current_prefix          <- px
        last_number             <- num
        image_df$donor[r]       <- NA_character_
        image_df$break_case[r]  <- TRUE
      }
    }

    # -----------------------------------------------------------------------
    # Propagate full symbol sets
    # -----------------------------------------------------------------------
    prop_list <- vector("list", nrow(image_df))

    for (r in seq_len(nrow(image_df))) {

      img   <- image_df$file_name[r]
      donor <- image_df$donor[r]

      if (!is.na(donor)) {
        # inherit symbols from donor image
        donor_rows <- long_df[
          long_df$file_name == donor &
            !is.na(long_df$text) & long_df$text != "",
          ,
          drop = FALSE
        ]

        if (nrow(donor_rows) == 0L) {
          df_img <- tibble(
            file_name   = img,
            index       = NA_integer_,
            code_format = NA_character_,
            text        = NA_character_,
            type        = NA_character_
          )
          df_img$decode_status <- NA_character_
          df_img$donor_file    <- NA_character_
        } else {
          df_img <- donor_rows
          df_img$file_name <- img
          df_img$full_path <- file.path(image_df$dir[r], img)
          df_img$dir       <- image_df$dir[r]
          if (donor == img) {
            df_img$decode_status <- "decoded"
            df_img$donor_file    <- NA_character_
          } else {
            df_img$decode_status <- "propagated"
            df_img$donor_file    <- donor
          }
        }

      } else {
        # no donor: use original decoded rows
        this_rows <- long_df[long_df$file_name == img, , drop = FALSE]

        if (nrow(this_rows) == 0L) {
          df_img <- tibble(
            file_name   = img,
            index       = NA_integer_,
            code_format = NA_character_,
            text        = NA_character_,
            type        = NA_character_
          )
        } else {
          df_img <- this_rows
        }

        # For break-case images with no decoded symbol: set code_format to the
        # sentinel "unknown" so that incremental reruns skip this image.
        # Leave text and type as NA.
        if (isTRUE(image_df$break_case[r])) {
          no_symbols <- all(
            (is.na(df_img$code_format) | df_img$code_format == "") &
              (is.na(df_img$text)        | df_img$text        == "") &
              (is.na(df_img$type)        | df_img$type        == "")
          )
          if (no_symbols) {
            df_img$code_format <- "unknown"
          }
          df_img$decode_status <- "undecodable"
        } else {
          df_img$decode_status <- "decoded"
        }

        df_img$donor_file <- NA_character_
      }

      prop_list[[r]] <- df_img
    }

    long_df_prop <- dplyr::bind_rows(prop_list)

    # -----------------------------------------------------------------------
    # Optional biomaterial lookup (requires a live Yugabyte connection)
    # -----------------------------------------------------------------------
    if (!is.null(con)) {
      lookup_codes <- unique(long_df_prop$text[
        !is.na(long_df_prop$text) &
          nzchar(long_df_prop$text)
      ])
      if (length(lookup_codes) > 0L) {
        message("  Looking up biomaterial names for ", length(lookup_codes),
                " unique code(s)...")
        lkp <- tryCatch(
          lookup_biomaterial_name(lookup_codes, con),
          error = function(e) {
            warning("lookup_biomaterial_name() failed: ", conditionMessage(e)); NULL
          }
        )
        if (!is.null(lkp) && nrow(lkp) > 0L) {
          lkp_sel <- lkp[, intersect(
            c("code", "scion_name", "scion_genotype", "location_name", "location_address"),
            names(lkp)
          ), drop = FALSE]
          long_df_prop <- dplyr::left_join(long_df_prop, lkp_sel,
                                           by = c("text" = "code"))
        }
      }
    }

    # -----------------------------------------------------------------------
    # Join back to workbook (1-to-many)
    # -----------------------------------------------------------------------
    join_cols <- intersect(
      c("file_name", "index", "code_format", "text", "type",
        "decode_status", "donor_file",
        "scion_name", "scion_genotype", "location_name", "location_address"),
      names(long_df_prop)
    )

    if (length(already_done) > 0L) {
      # Incremental: preserve the fully-enriched rows for old images and
      # only join decoded results for the newly processed images.
      old_enriched <- df_orig[df_orig$file_name %in% already_done, , drop = FALSE]

      new_barcodes <- long_df_prop[
        long_df_prop$file_name %in% new_names, join_cols, drop = FALSE
      ]
      new_joined <- dplyr::left_join(df_to_decode, new_barcodes, by = "file_name")

      # bind_rows fills any column mismatch with NA
      joined_df <- dplyr::bind_rows(old_enriched, new_joined)

    } else {
      barcodes  <- long_df_prop[, join_cols, drop = FALSE]
      joined_df <- df_orig |> dplyr::left_join(barcodes, by = "file_name")
    }

    message("  Writing updated CSV...")
    readr::write_csv(joined_df, csv_file)

    results[[i]] <- joined_df
  }

  message("\nAll files processed.")
  invisible(results)
}
